#!/bin/bash
echo "Must be ran as root"

sudo apt-get install python-nmap
sudo easy_install netifaces
pip install faker
pip install termcolors
pip install python-whois

echo "Finished installing"
echo "Thanks for installing netpwn"
echo "Run netpwn by typing the command netpwn"
